### ISSUE TITLE
Installation issue: No module named 'ModColor'

### ISSUE THREAD

**Issue by IanHeywood** [bennahugo/catdagger#3]
I'm getting this issue with a fresh installation inside a venv:

```
(py3) ianh@ubuntu:~/Software$ dagger -h
Traceback (most recent call last):
  File "/home/ianh/venv/py3/bin/dagger", line 3, in <module>
    from catdagger import __main__ as driver
  File "/home/ianh/venv/py3/lib/python3.6/site-packages/catdagger/__main__.py", line 27, in <module>
    from catdagger import logger
  File "/home/ianh/venv/py3/lib/python3.6/site-packages/catdagger/logger.py", line 10, in <module>
    import ModColor
ModuleNotFoundError: No module named 'ModColor'
```

ModColor seems to be something from DDFacet, which is also installed in this venv. Am I missing something?

Cheers.

**Comment by bennahugo** [comment]
This is still 2.7 Ian.gqt

**Comment by bennahugo** [comment]
Sorry dog jumped on me while I was writing that lol.

Module is still 2.7. it is super sensitive to the sigma - there is no sigma
that just works well. Like masking it takes a bit of tweaking and checking
what is tagged and what not

Ideas on how to improve this is welcome

**Comment by IanHeywood** [comment]
Thanks Ben, I will try a 2.7 installation.

I'm mainly trying to learn how to use the degridder in CubiCal. I'm not sure how MS columns / DicoModels / LSMs / regions all play together when defining the CubiCal model, so I thought the easiest way to learn would be to follow the steps in your vermeerkat recipe. But I will play around with catdagger and let you know if I can think of any tricks.

**Comment by bennahugo** [comment]
If you store polygons in physical (pixel) format you don't need to use
catdagger. Just fyi
